# Generated by Django 5.0.7 on 2024-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_privacypolicy_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
