# Generated by Django 5.0.7 on 2024-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_privacypolicy_last_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
